### ISSUE TITLE
Excluding folders from sync

### ISSUE THREAD

**Issue by fonnesbeck** [yoichiro/chromeos-filesystem-dropbox#100]
Most Dropbox syncing services allow for folders to be excluded from sync, so that large unwanted files do not sync to devices with low capacity. Is there a way of enabling this on Chrome?

**Comment by fonnesbeck** [comment]
Is this application still supported?

**Comment by yoichiro** [comment]
This software never sync directories and files. Instead, when users request to access to each it, this software fetches it to the user's computer.
