### ISSUE TITLE
Dropbox Mounting Does not Work

### ISSUE THREAD

**Issue by LordStryfe1** [yoichiro/chromeos-filesystem-dropbox#103]
Getting failed to launch authentication when I try to mount the File System Drop Box.  Any support for this?

**Comment by peachsb3** [comment]
I'm having the same issue on my Asus Chromebook.  I've uninstalled an reinstalled and same thing.  Failure to launch authentication.  Anyone have a fix??

**Comment by rdcowan** [comment]
I am also having the same issue.  I even reset (Powerwashed) my Samsung Chromebook and reloaded everything and I get the same message:  ‘Failed to mount. Authorization page could not be loaded.’

There seems to be a lot of this going around when I did an online search.  There's got to be a fairly simple solution.  Sounds like a communication problem between the extension and Dropbox.

**Comment by yoichiro** [comment]
Duplicated #120. Close this issue, and I treat this issue on the #120. Thank you for the reporting!
