### ISSUE TITLE
Mounts fine but doesn't show my folders

### ISSUE THREAD

**Issue by alattetalk** [yoichiro/chromeos-filesystem-dropbox#121]
I have a personal dropbox account and a business account, linked.  Mounting seems to work fine, it prompts me to select either personal or business.  Mounts successfully, I can see the folder in my files but it only contains the dropbox info pages, not my files or folders that are actually in my dropbox. Help?!

**Comment by yoichiro** [comment]
Unfortunately, I don't have a business account. Therefore, I can't implement a feature for a business account. Sorry.
