### ISSUE TITLE
Hitting the mount button continuously doesn't work for me.

### ISSUE THREAD

**Issue by marshameine** [yoichiro/chromeos-filesystem-dropbox#122]
I've tried this many times.

**Comment by marshameine** [comment]
i anything being done to fix this?

**Comment by rdcowan** [comment]
Yes, The author of the program (yoichiro) is working with Google to
find out what may have occurred with a ChromeOS update to cause the
problem.

 -------Original Message-------

**Comment by andychambers30** [comment]
Im having the same issue with this - is there any update on it?

**Comment by rdcowan** [comment]
-------Original Message-------

**Comment by rdcowan** [comment]
Yoichiro, Is a solution on the way? It worked so well before these
issues...

 Thanks! 

Robert 

 -------Original Message-------

**Comment by yoichiro** [comment]
Duplicated issue: #120
