### ISSUE TITLE
Thanks so much!! + Suggestion

### ISSUE THREAD

**Issue by Watney** [yoichiro/chromeos-filesystem-dropbox#27]
Hello, 

Firstly, thanks for offering this cool integration for Dropbox. Awesome!!

It might increase the acceptance if there was a way that the user could verify that s/he was logging into the Dropbox site, and not submitting his/her credentials to some bogus site. The authentication page presents itself in a clean page without any way to know where the credentials are actually going. 

Of course, one could always review the code, but maybe there's a way to increase confidence. Thanks again!!

**Comment by yoichiro** [comment]
@Watney Hmm... I cannot understand your opinion enough. Users can confirm whether the user approved Dropbox API call from the following page:

https://www.dropbox.com/account#security

This application  is only using the chrome.identity API to apply OAuth2 Implicit grant flow. That is, I cannot customize the flow. But, I think that I can put the link above on the window of this application.

Could you tell me more clear solution?

**Comment by Watney** [comment]
@yoichiro the actual link at the top of the window sounds like a great idea. The basic idea is to assure the user that this isn't a man-in-the-middle spoof, redirecting the credentials to a 3rd-party and before sending them to Dropbox. 

Please, please don't misunderstand me. This has *absolutely nothing* to do with you personally. Rather, it's good judgment (in my opinion) given the around of fraud today.

**Comment by Watney** [comment]
@yoichiro please take a look at [Dropbox for Gmail](https://chrome.google.com/webstore/detail/dropbox-for-gmail-beta/dpdmhfocilnekecfjgimjdeckachfbec?hl=en). When you install the plugin the authentication URL is clearly presented. This gives the user more confidence. Thanks again!!

**Comment by yoichiro** [comment]
@Watney The Dropbox for Gmail extension provides by Dropbox officially, therefore, the extension can use the cookie value issued for Dropbox domain to establish the session. That is, the extension doesn't use OAuth2. My application should/must not access the cookie,  because my application is unofficial application. As I mentioned, my application uses OAuth2 authorization flow provided by Dropbox and uses the chrome.identity API simply.

**Comment by yoichiro** [comment]
Add the link on the bottom of the window to open the Dropbox linked applications page. #32

**Comment by yoichiro** [comment]
@Watney I have just released the new version 1.1.0 which has the link to open the Dropbox linked applications page. I close this issue. Thank you for the proposal!
