### ISSUE TITLE
Trouble Launching the app

### ISSUE THREAD

**Issue by jessicakmccurdy** [yoichiro/chromeos-filesystem-dropbox#28]
I am not being given the option to "mount" to the file manager. When I launch the app nothing is happening.

**Comment by yoichiro** [comment]
@jessicakmccurdy I cannot understand the situation. Could you describe more detail? For instance, your environment (including ChromeOS version number), steps to reproduce, output contents which can confirm on the DevTools Console tab, and etc.

**Comment by AlanNeal** [comment]
Hello. I believe I encountered the same issue. The app window opened with the logo and the wording, however, there was no "Mount" link below. It occurred to me that my display settings were the cause. I'm using a Chromebox with a large TV and, since I sit far away, I have the font size set to Very Large. At that setting, the "Mount" line is truncated. Once I reduced the font size I could see the link.

**Comment by yoichiro** [comment]
@AlanNeal Thank you for your report! Well, I guess that I need to adjust the style against each UI...
@jessicakmccurdy I guess that your situation was the same as the AlanNeal's situation...Could you confirm the font setting?

**Comment by AlanNeal** [comment]
@yoichiro: I suppose you could just start with a bigger window that covers the worst case. I have never done development for ChromeOS, but on a web I'd simply have a full-size table (or a div set like one) and have a single cell set to horizontally and vertically center the contents. On my screen, it looks like it just misses by a 100px or so (wild guess). If the window were just a bit taller, I think you'd be set. I use your sFTP app, by the way. It's awesome. If you move the Dropbox app in that direction, as in accommodating multiple accounts, the problem would solve itself.

**Comment by yoichiro** [comment]
@jessicakmccurdy @AlanNeal Could you put the screenshot when you faced this issue here?

**Comment by AlanNeal** [comment]
Screen set to Very Large font...
![01 screen set to very large font](https://cloud.githubusercontent.com/assets/203566/6793821/5b737874-d187-11e4-90bf-c83727730cab.png)

Initial app window with Very Large font...
![02 initial app window with very large font](https://cloud.githubusercontent.com/assets/203566/6793824/5b74609a-d187-11e4-977f-aaa189a13ba2.png)

App window after pressing tab...
![03 app window after pressing tab](https://cloud.githubusercontent.com/assets/203566/6793822/5b73a1a0-d187-11e4-877b-a239dcaebc43.png)

Changing to Medium font...
![04 changing to medium font](https://cloud.githubusercontent.com/assets/203566/6793823/5b73e066-d187-11e4-81a9-c8fb319ffe32.png)

Initial app window with medium font...
![05 initial app window with medium font](https://cloud.githubusercontent.com/assets/203566/6793820/5b733eb8-d187-11e4-9628-b50d51787736.png)

**Comment by yoichiro** [comment]
@AlanNeal Thank you for posting images! I'll fix this issue at next version.

**Comment by yoichiro** [comment]
@jessicakmccurdy @AlanNeal I have just released the new version 1.0.1 to fix this issue. The diff is #30. Thank you for the reportings!

**Comment by AlanNeal** [comment]
@yoichiro: My pleasure. I look forward to trying the new release.
