### ISSUE TITLE
Increase App user limit

### ISSUE THREAD

**Issue by beaufortfrancois** [yoichiro/chromeos-filesystem-dropbox#3]
Here's what I'm seeing after logging into Dropbox:

*This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.*

![screenshot 2015-02-05 at 6 21 54 pm](https://cloud.githubusercontent.com/assets/634478/6065241/eb2aff70-ad63-11e4-846e-76cfefb1cc4e.png)

**Comment by yoichiro** [comment]
@beaufortfrancois Sorry, this product is currently in developing, therefore, the Dropbox API can access with my account only. When I release this provider, of course, someone can access to the Dropbox API and this will work on your account.

**Comment by beaufortfrancois** [comment]
Looking forward to see being released then!

In the mean time, I'm gonna create my own dropbox API console app so that I can play with your cool Chrome App ;)

**Comment by beaufortfrancois** [comment]
And it's working great!
Thanks @yoichiro 
![screenshot 2015-02-09 at 7 42 46 pm](https://cloud.githubusercontent.com/assets/634478/6112934/e3a83eba-b093-11e4-8ec4-086f19cacbf2.png)
