### ISSUE TITLE
Setting Dropbox as the destination for file downloads results in a "Download error"

### ISSUE THREAD

**Issue by noahleigh** [yoichiro/chromeos-filesystem-dropbox#34]
Not sure if this is a problem with Chrome OS or the app. There is no other error information provided that I am aware of.

**Comment by yoichiro** [comment]
@noahleigh I guess that the Chrome Web browser has a bug about this. I have already reported this issue to the crbug: https://code.google.com/p/chromium/issues/detail?id=458757
