### ISSUE TITLE
Dropbox Folder Issue

### ISSUE THREAD

**Issue by turbotgu** [yoichiro/chromeos-filesystem-dropbox#35]
I have successfully mounted the dropbox. It shows up in my file system, and I am able to see the first level of folders in my dropbox. However, I cannot access anything past the first level of folders in my dropbox. I can select the folders but not open them. The file system essentially freezes up. I have tried restarting my device but that did not change anything.

**Comment by yoichiro** [comment]
@turbotgu I cannot understand your situation. Probably, some error occurred. Could you check the Console Log on the DevTools using the way described below?

https://github.com/yoichiro/chromeos-filesystem-dropbox/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by turbotgu** [comment]
I followed the instructions from the link. Here is the result.

![screenshot 2015-04-07 at 7 24 05 pm](https://cloud.githubusercontent.com/assets/11828929/7035900/d07ca6c4-dd5b-11e4-98cd-0ad271f376ac.png)

**Comment by yoichiro** [comment]
@turbotgu It seems that there is no error... Could you re-capture the console log after you enter the directory where this issue is reproduced?

**Comment by turbotgu** [comment]
Sorry for the delay. My chromebook installed an update today and after I re-mounted the dropbox, it started working properly.

**Comment by yoichiro** [comment]
@turbotgu I see, close this issue. If you find some issue again, register it as a new issue. Thank you for the reporting.
