### ISSUE TITLE
Mount Dropbox "Failed" Message after allowing access to the files and folders in your Dropbox

### ISSUE THREAD

**Issue by hcoffey** [yoichiro/chromeos-filesystem-dropbox#43]
I successfully downloaded File System for Dropbox. When I run the app, and attempt to mount my Dropbox account, I successfully get logged in to Dropbox, but then get a failed message after giving permission to Allow access to the files and folders in your Dropbox. When I look at the Dropbox linked applications list, File System for ChromeOS shows in the list as Access Type: Full Dropbox. 
![screenshot 2015-06-17 at 12 00 51 pm](https://cloud.githubusercontent.com/assets/12938925/8212294/e2db5d8c-14e8-11e5-9dfb-94bbe0caad99.png)

**Comment by yoichiro** [comment]
@hcoffey Probably, some error occurred. Could you confirm the debug log on the console tab of the DevTools by the steps: https://github.com/yoichiro/chromeos-filesystem-dropbox/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
I close this issue because @hcoffey didn't provide the logs to fix this issue.
