### ISSUE TITLE
Error: status=0

### ISSUE THREAD

**Issue by jrapo** [yoichiro/chromeos-filesystem-dropbox#49]
Hi! I just installed the extension on my chromebook and I keep getting notifications from the extension saying "Error: status=0"
This happens pretty much every time when I wake the computer, so these keep piling on the notification center.

**Comment by jrapo** [comment]
![screenshot 2015-06-26 at 17 36 31](https://cloud.githubusercontent.com/assets/13070546/8387838/e7ccc7b6-1c29-11e5-80b5-7083db1223e7.png)

**Comment by jrapo** [comment]
Seems that background is trying to refresh before the connection is re-established when waking up?

**Comment by markwinspear** [comment]
I'm also seeing this. My chromebook connects to a work network that requires a username and password. The app is trying to connect before I can complete the process leading to a pile-up of notifications

**Comment by yoichiro** [comment]
Sorry, I thought same thing. I intend to modify to not display the notification popup.

**Comment by yoichiro** [comment]
I have just release a new version 1.1.6. This version includes a code #50 to fix this issue. That is, displaying notification will be avoided. I close this issue. @jrapo @markwinspear Thank you for this reporting!
