### ISSUE TITLE
Use chrome.identity.getRedirectUrl

### ISSUE THREAD

**Issue by beaufortfrancois** [yoichiro/chromeos-filesystem-dropbox#5]
You might want to use `chrome.identity.getRedirectURL()` when defining `AUTH_URL` at https://github.com/yoichiro/chromeos-filesystem-dropbox/blob/7c1b6a8d03c4bbbadbb75da771479eebe0bc81f4/dropbox_client.js#L5-L5

See https://developer.chrome.com/apps/identity#method-getRedirectURL

**Comment by yoichiro** [comment]
Yes, your mention is currect. I modified the AUTH_URL definition to use the API. You can confirm the diff at: https://github.com/yoichiro/chromeos-filesystem-dropbox/pull/7

**Comment by yoichiro** [comment]
@beaufortfrancois I agree your comment. Modified: https://github.com/yoichiro/chromeos-filesystem-dropbox/pull/7, could you confirm the diff?

**Comment by beaufortfrancois** [comment]
LGTM ;)

**Comment by yoichiro** [comment]
Thanks!
