### ISSUE TITLE
Selective Sync

### ISSUE THREAD

**Issue by swt83** [yoichiro/chromeos-filesystem-dropbox#52]
Does this app actually download any files to my local machine?

If not, then selective sync isn't necessary.  If so, then I would need to know if selective sync works with your app since my Dropbox would be bigger than my current hard drive.

**Comment by yoichiro** [comment]
@swt83 Basically, this app does not download each file until a user want to open the file. As an exception, a Files app will download an image file content to create the thumbnail.

**Comment by yoichiro** [comment]
Close this issue.
