### ISSUE TITLE
Can't overwrite file by copy paste or drag and drop.

### ISSUE THREAD

**Issue by yeswap** [yoichiro/chromeos-filesystem-dropbox#58]
Great app thanks for building it. 

I like to make a feature request.

When copying a file into the Dropbox folder please provide an option to overwrite an existing file of the same name.

If I copy a file from the Dropbox folder to the ChromeOS and edit it offline and then copy the edited  version back to Dropbox it creates a new copy of the file with a new name that includes a number.

For example if I download example.txt, edit it and copy it back to Dropbox, a new file , example(1).txt is created rather than replacing example.txt with the new version.

Thanks

**Comment by yoichiro** [comment]
@yeswap If you want to get such feature, you should file the feature request like above to crbug.com. I think that I cannot support such feature by each File System Provider API implementations.

**Comment by yeswap** [comment]
OK thanks for the reply.
