### ISSUE TITLE
This plugin only works in chromium OS... I tried in mac chrome browser..but it did not work..Could you please tell me why there is a limitation

### ISSUE THREAD

**Issue by mausumi345** [yoichiro/chromeos-filesystem-dropbox#61]

**Comment by yoichiro** [comment]
@mausumi345 Because the chrome.fileSystemProvider API is provided for ChromeOS only. https://developer.chrome.com/apps/fileSystemProvider If you can make sense, please close this issue.

**Comment by mausumi345** [comment]
Can we make it compatible for other OS

**Comment by yoichiro** [comment]
@mausumi345 You can send such proposal to [crbug.com](http://crbug.com). I close this issue.
