### ISSUE TITLE
Transferring files with a pound-sign in the name results in an error copying.

### ISSUE THREAD

**Issue by broxen** [yoichiro/chromeos-filesystem-dropbox#62]
When transferring files from my google drive to dropbox, or vise versa, files with a pound sign result in an error.

Renaming the file without the '#' allows transfer to complete successfully.

**Comment by yoichiro** [comment]
@broxen That is, you could not copy your file which the name includes the '#' character, right?

**Comment by yoichiro** [comment]
@broxen I could not reproduce this issue.
