### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by spiritracker** [yoichiro/chromeos-filesystem-dropbox#66]
![screenshot 2016-10-12 at 82042 pm](https://cloud.githubusercontent.com/assets/1784145/19332402/9b4428c0-90b9-11e6-947e-a9d06da7bd26.jpg)

I am getting this login screen after clicking "mount." I have no idea what I'm logging into or what password to use.

**Comment by yoichiro** [comment]
Probably, you need to fill in your user credential to use the proxy server to communicate from your machine to external servers.
