### ISSUE TITLE
command line specification for Dropbox files

### ISSUE THREAD

**Issue by jmlattis** [yoichiro/chromeos-filesystem-dropbox#67]
This is not a problem, only a question.
I have my Chromebook in developer mode.
Is it possible to specify a file name on the command line from either the shell prompt or the bash prompt?
If so, in which directory would I find the Dropbox files mounted?
Thanks.

**Comment by tomhallman** [comment]
@jmlattis Did you figure out the answer to your question?  I have the same one.  (Though I'm not in developer mode.)

**Comment by yoichiro** [comment]
At least, the chrome.fileSystemProvider API doesn't mount directly to the OS filesystem, I guess...
