### ISSUE TITLE
File icon thumbnail preview missing 

### ISSUE THREAD

**Issue by edsturdy** [yoichiro/chromeos-filesystem-dropbox#68]
Hi,
     I've noticed that my Google Drive folder on Chrome OS displays thumbnail previews of many file types. 
In the dropbox folder thumbnails are't displayed for PDF files, although image files show a thumbnail. Do you think it would be possible to add PDF thumbnail view in future releases ?

**Comment by yoichiro** [comment]
Unfortunately, the answer is no. Dropbox API doesn't support to provide the thumbnail image for PDF. See: https://www.dropbox.com/developers/documentation/http/documentation#files-get_thumbnail

> This method currently supports files with the following file extensions: jpg, jpeg, png, tiff, tif, gif and bmp.
