### ISSUE TITLE
mounted but no access to dropbox

### ISSUE THREAD

**Issue by jsavo** [yoichiro/chromeos-filesystem-dropbox#75]
i have succesfukky mounted but i have no access to dropbox.  when the system folder loads dropbox is not an option.  when i go back and hit the mount button i get an error stating it is already mounted.

**Comment by yoichiro** [comment]
@jsavo Hmm... I would like to know more details. Well, Did you see the following screen?

* The login screen of Dropbox to fill in your email address and password.
* The authorization screen to grant the access for your files of Dropbox.
* The popup notification to let you know about completion of mounting the Dropbox.

Thank you for the reporting.

**Comment by jsavo** [comment]
Hello

Yes i did see all three of those. I have noticed that it only happens on the save as function in chrome with a PDF. I have tried to work around getting the PDF to open in adobe reader but have had no luck.  Let me know if you need any other screen shots or info

Thanks

**Comment by yoichiro** [comment]
@jsavo I think that the issue causes by the Chrome Web Browser.
