### ISSUE TITLE
Google sign-in not working

### ISSUE THREAD

**Issue by kmarko** [yoichiro/chromeos-filesystem-dropbox#87]
After clicking the "Sign in with Google" button on the login screen, it returns to the Mount screen with a message stating "Authorization page could not be loaded".

**Comment by yoichiro** [comment]
@kmarko Hmm... The login screen and the screen to sign in with Google are displayed from the Dropbox Server. In addition, the screens are opened by calling chrome.identity API from my app. That is, this issue is depending on the Dropbox and Chrome OS. Thus, I can't fix this issue, I think. Sorry.
