### ISSUE TITLE
Dropbox not mounting

### ISSUE THREAD

**Issue by norfolkbumpkin** [yoichiro/chromeos-filesystem-dropbox#98]
Hi, having the same problem repeatedly with mounting on my Chromebook; have uninstalled and installed a number of times but problem still persists.

When I click 'mount', the green dialogue box appears ('Attempting to mount instance...') and then very briefly the Dropbox login page flashes up.... before disappearing in a flash and I get a red dialogue box telling me '**Failed to mount** Authorisation page could not be loaded.

Any advice please?
Thanks,
Alex

**Comment by JoeArmstrong** [comment]
Similar problem here - I don't see a DropBox page pop up though - just the failure message

**Comment by Falcon124** [comment]
Same here, as per my comment on Issue #99.

**Comment by yoichiro** [comment]
Duplicated #120. Close this issue, and I treat this issue on the #120. Thank you for the reporting!
