### ISSUE TITLE
Dropbox Fails to Mount - Authorization Page Failed to Load

### ISSUE THREAD

**Issue by pajjs4** [yoichiro/chromeos-filesystem-dropbox#99]
I'm attempting to use the File System for Dropbox Chrome OS extension. I am having trouble setting it up, as I continue to get this message:

Dropbox failed to mount...
Authorization page failed to load

**Comment by claphands** [comment]
I had this problem a week ago, but it seems to have been fixed! Try again and report back?

**Comment by mccyclone** [comment]
I am currently experiencing this issue. Tried uninstall and reinstall.
![Screenshot 2019-12-01 at 4 38 03 PM](https://user-images.githubusercontent.com/3957724/69921612-1da1a880-1459-11ea-81c8-b49e97603faf.png)

**Comment by theaulddubliner** [comment]
Same for me.

**Comment by mherman95** [comment]
I am having the same issue as well.  It works for a Chromebook that I already had it set up months ago but my new one will give me this error when trying to mount Dropbox through the "Files" app.  Any ideas?

**Comment by Falcon124** [comment]
Also happening for me on a new Acer Chromebook 315. Used to work fine on my older one but this new one flashes the login page briefly, then it closes and displays the failure message with "Authorization page could not be loaded." as per mccyclone above.

I'm running Chrome OS 79.0.3945.86 (Official Build) (64 bit)

Could this be linked to the latest version of Chrome OS as it wasn't happening on the earlier version my other Chromebook was running when I first ran the Dropbox File System app?

**Comment by mherman95** [comment]
Mine is happening on my new Acer Chromebook 715 that I purchased last week.

Matt Herman

________________________________

**Comment by rdcowan** [comment]
I've got the same problem on my Samsung Chromebook.  I did a factory reset (Powerwash) and re-initialized it and still the same error.  The problem seems to be widespread as I found quite a few references to it when I searched online.  I'm running Chrome 79.0.3945.86 as of 12/23/19
Somebody has to know where this error message is generated...

**Comment by mherman95** [comment]
My Samsung Chromebook still has it working weirdly enough. It must be an issue the developer has. Hopefully they can resolve it quickly as it is a very helpful tool.

Matt Herman

________________________________

**Comment by timmilazzo** [comment]
Facing the same issue on my new ASUS Chromebook C425. Version 79.0.3945.86 (Official Build) (64-bit)

**Comment by yoichiro** [comment]
Duplicated #120. Close this issue, and I treat this issue on the #120. Thank you for the reporting!
